name: release

on:
  push:
    branches:
      - master

permissions:
  contents: write
  packages: write

jobs:
  compile-and-upload:
    name: Compile and upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Building
        run: |
          python -m compileall .
      - name: Make zip directory
        run: |
          mkdir compiled
          mv **/*.pyc compiled
          zip -r compiled.zip compiled

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
      - name: Publishing
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./compiled.zip
          asset_name: compiled.zip
          asset_content_type: application/zip